In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [2]:
df=pd.read_csv('Datasets\diabetes.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [4]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
df.duplicated().sum()

0

In [6]:
df['BMI']=np.where(df['BMI']>30,'o',np.where(df['BMI']>26,'ow',np.where(df['BMI']>18,'nw','uw')))

In [7]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,o,0.627,50,1
1,1,85,66,29,0,ow,0.351,31,0
2,8,183,64,0,0,nw,0.672,32,1
3,1,89,66,23,94,ow,0.167,21,0
4,0,137,40,35,168,o,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,o,0.171,63,0
764,2,122,70,27,0,o,0.340,27,0
765,5,121,72,23,112,ow,0.245,30,0
766,1,126,60,0,0,o,0.349,47,1
767,1,93,70,31,0,o,0.315,23,0

In [8]:
df=pd.get_dummies(df)

In [9]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,DiabetesPedigreeFunction,Age,Outcome,BMI_nw,BMI_o,BMI_ow,BMI_uw
0,6,148,72,35,0,0.627,50,1,0,1,0,0
1,1,85,66,29,0,0.351,31,0,0,0,1,0
2,8,183,64,0,0,0.672,32,1,1,0,0,0
3,1,89,66,23,94,0.167,21,0,0,0,1,0
4,0,137,40,35,168,2.288,33,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,0.171,63,0,0,1,0,0
764,2,122,70,27,0,0.340,27,0,0,1,0,0
765,5,121,72,23,112,0.245,30,0,0,0,1,0
766,1,126,60,0,0,0.349,47,1,0,1,0,0
767,1,93,70,31,0,0.315,23,0,0,1,0,0

In [10]:
y=df['Outcome']
x=df.drop('Outcome',axis=1)

In [11]:
print(x.shape)
print(y.shape)

(768, 11)
(768,)

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [13]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [14]:
print(y_pred)

[1 0 1 0 0 0 0 1 0 0 0 0 1 1 0 1 1 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1
 1 1 0 0 0 0 0 1 0 1 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 1 0 0 1 0 1 0 0 1 1 1 1 1 0 0 1 0 0 0 0 1 0 0 1 0 0 1 1 0 0 1 0 1 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 1 1 1 1 0 0 0 1 1 0 0 1
 1 0 0 0 1 0]

In [15]:
accuracy_score(y_test,y_pred)

0.6558441558441559

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [17]:
scaler=StandardScaler()
scaler.fit(x_train)

StandardScaler()

In [18]:
x_train_scaled=scaler.transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [19]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(x_train_scaled,y_train)
y_pred=model.predict(x_test_scaled)

In [20]:
print(y_pred)

[0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1
 0 0 1 1 0 0 0 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 1 0
 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 1 1 1 0 0 0 1 1 1 1 0 0 1 0 1 0 0 1
 1 0 0 0 0 0]

In [21]:
accuracy_score(y_test,y_pred)

0.7142857142857143

In [22]:
KNeighborsClassifier??

In [23]:
LinearRegression??

In [27]:
y_actual=['dog','cat','dog','cat','dog','cat']
y_predict=['dog','cat','cat','dog','cat','cat']

In [30]:
confusion_matrix(y_actual,y_predict,labels=['cat','dog'])

array([[2, 1],
       [2, 1]], dtype=int64)

In [29]:
y_actual=['dog','cat','dog','cat','dog','cat']
y_predict=['dog','cat','cat','dog','cat','cat']

In [31]:
confusion_matrix(y_actual,y_predict,labels=['dog','cat'])

array([[1, 2],
       [1, 2]], dtype=int64)

In [33]:
print(classification_report(y_actual,y_predict))

              precision    recall  f1-score   support

         cat       0.50      0.67      0.57         3
         dog       0.50      0.33      0.40         3

    accuracy                           0.50         6
   macro avg       0.50      0.50      0.49         6
weighted avg       0.50      0.50      0.49         6

In [34]:
confusion_matrix??

In [35]:
y_actual=['10','9','10','10','10','10','10','10','10','9']
y_predict=['10','10','10','10','10','10','10','9','10','9']

In [36]:
confusion_matrix(y_actual,y_predict,labels=['10','9'])

array([[7, 1],
       [1, 1]], dtype=int64)

In [37]:
print(classification_report(y_actual,y_predict))

              precision    recall  f1-score   support

          10       0.88      0.88      0.88         8
           9       0.50      0.50      0.50         2

    accuracy                           0.80        10
   macro avg       0.69      0.69      0.69        10
weighted avg       0.80      0.80      0.80        10